In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("../data/raw/Walmart.csv")

In [3]:
df["Date"] = pd.to_datetime(df["Date"], dayfirst=True)

In [4]:
df["Year"] = df["Date"].dt.year
df["Month"] = df["Date"].dt.month
df["Week"] = df["Date"].dt.isocalendar().week

# for time series the data should be sorted according to date

In [5]:
df = df.sort_values("Date")

In [6]:
df[["Date", "Weekly_Sales"]].head()

           Date  Weekly_Sales
0    2010-02-05    1643690.90
1287 2010-02-05    2193048.75
5148 2010-02-05     536006.73
2288 2010-02-05     789036.02
4147 2010-02-05     465108.52

In [7]:
df[["Date", "Weekly_Sales"]].tail()

           Date  Weekly_Sales
3574 2012-10-26     688940.94
714  2012-10-26     319550.77
5719 2012-10-26     921264.52
2573 2012-10-26    1127516.25
6434 2012-10-26     760281.43

In [8]:
df = df.sort_values("Date").reset_index(drop=True)

# creating lag features

In [9]:
df["Lag_1"] = df["Weekly_Sales"].shift(1)

In [10]:
df[["Date", "Weekly_Sales", "Lag_1"]].head(10)

        Date  Weekly_Sales       Lag_1
0 2010-02-05    1643690.90         NaN
1 2010-02-05    2135143.87  1643690.90
2 2010-02-05    1469252.05  2135143.87
3 2010-02-05     477409.30  1469252.05
4 2010-02-05    1528008.64   477409.30
5 2010-02-05     467546.74  1528008.64
6 2010-02-05     543384.01   467546.74
7 2010-02-05     317173.10   543384.01
8 2010-02-05     647029.28   317173.10
9 2010-02-05    1672352.29   647029.28

In [12]:
df["Lag_2"] = df["Weekly_Sales"].shift(2)
df["Lag_4"] = df["Weekly_Sales"].shift(4)

In [13]:
df[["Weekly_Sales", "Lag_1", "Lag_2", "Lag_4"]].head(10)

   Weekly_Sales       Lag_1       Lag_2       Lag_4
0    1643690.90         NaN         NaN         NaN
1    2135143.87  1643690.90         NaN         NaN
2    1469252.05  2135143.87  1643690.90         NaN
3     477409.30  1469252.05  2135143.87         NaN
4    1528008.64   477409.30  1469252.05  1643690.90
5     467546.74  1528008.64   477409.30  2135143.87
6     543384.01   467546.74  1528008.64  1469252.05
7     317173.10   543384.01   467546.74   477409.30
8     647029.28   317173.10   543384.01  1528008.64
9    1672352.29   647029.28   317173.10   467546.74

In [14]:
df["Rolling_Mean_4"] = df["Weekly_Sales"].rolling(window=4).mean()

In [15]:
df[["Weekly_Sales", "Rolling_Mean_4"]].head(10)

   Weekly_Sales  Rolling_Mean_4
0    1643690.90             NaN
1    2135143.87             NaN
2    1469252.05             NaN
3     477409.30    1.431374e+06
4    1528008.64    1.402453e+06
5     467546.74    9.855542e+05
6     543384.01    7.540872e+05
7     317173.10    7.140281e+05
8     647029.28    4.937833e+05
9    1672352.29    7.949847e+05

In [16]:
df["Rolling_Std_4"] = df["Weekly_Sales"].rolling(window=4).std()

In [17]:
df[["Weekly_Sales", "Rolling_Mean_4", "Rolling_Std_4"]].head(10)

   Weekly_Sales  Rolling_Mean_4  Rolling_Std_4
0    1643690.90             NaN            NaN
1    2135143.87             NaN            NaN
2    1469252.05             NaN            NaN
3     477409.30    1.431374e+06  695666.081647
4    1528008.64    1.402453e+06  686238.075721
5     467546.74    9.855542e+05  592948.395051
6     543384.01    7.540872e+05  517044.912663
7     317173.10    7.140281e+05  550736.076175
8     647029.28    4.937833e+05  138833.330104
9    1672352.29    7.949847e+05  600908.070227

In [18]:
df.isnull().sum()

Store             0
Date              0
Weekly_Sales      0
Holiday_Flag      0
Temperature       0
Fuel_Price        0
CPI               0
Unemployment      0
Year              0
Month             0
Week              0
Lag_1             1
Lag_2             2
Lag_4             4
Rolling_Mean_4    3
Rolling_Std_4     3
dtype: int64

In [19]:
df = df.dropna()

In [36]:
df.to_csv("../data/processed/featured_data.csv", index=False)

In [24]:
print(X.shape)
print(y.shape)

(6431, 14)
(6431,)